export const SET_USER_DETAILS = 'SET_USER_DETAILS';
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_DOCUMENTS = 'SET_DOCUMENTS';
export const UPDATE_DOCUMENT = 'UPDATE_DOCUMENT';
export const DELETE_DOCUMENT = 'DELETE_DOCUMENT';
export const SET_LOADER = 'SET_LOADER';
export const LOADER_TIMEOUT = 5000;
