export const SET_USER_DETAILS = 'SET_USER_DETAILS';
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_DOCUMENTS = 'SET_DOCUMENTS';
export const UPDATE_DOCUMENTS = 'UPDATE_DOCUMENTS';
